config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'main#home'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :categories do
    resources :tasks
  end
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :user
    has_many :tasks, dependent: :destroy

    validates :name, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update, :destroy]

    def index
        @categories = current_user.categories
    end

    def show
        @tasks = @category.tasks
        @task_due_today = @tasks.where(date: Date.today)
    end

    def new
        @category = current_user.categories.build
    end

    def edit
    end

    def create
        @category = current_user.categories.build(category_params)

        if @category.save
            redirect_to category_path(@category),
            notice: "Category was successfully created."
        else
            render :new
        end
    end
    
    def update
        if @category.update(category_params)
            redirect_to @category, notice: "Category was successfully updated."
        else
            render :edit
        end
    end

    def destroy
        @category.destroy
            redirect_to categories_path, notice: "Category was successfully destroyed."
    end

    private

        def category_params
            params.require(:category).permit(:name)
        end

        def set_category
            @category = current_user.categories.find_by(id: params[:id])
        end

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_category, only: [:index, :create, :new]
    before_action :set_task, only: [:show, :index, :edit, :update, :destroy]

    def index
        @tasks = @category.tasks
        @task_due_today = @category.tasks.where(date: Date.today)
    end

    def show
    end

    def new
       @task = @category.tasks.build
    end

    def edit
    end

    def create
        @task = @category.tasks.build(task_params)
        
        if @task.save
            redirect_to category_path(@category), notice: "Task was successfully created."
        else
            render :new, status: :unprocessable_entity
        end
    end

    def update
        if @task.update(task_params)
            redirect_to category_path(@category), notice: "Task was successfully updated."
        else
            render :edit
        end
    end

    def destroy
        @task.destroy
            redirect_to category_path(@category), notice: 'Task was successfully destroyed.'
    end

    private
        def set_category
            @category = current_user.categories.find(params[:category_id])
        end

        def task_params
            params.require(:task).permit(:title, :description, :date)
        end

        def set_task
            @category = current_user.categories.find(params[:category_id])
            @task = @category.tasks.find(params[:id])
        end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_category_list.html.erb
<% @categories.each do |category| %>
  <div class="w-56 h-32 m-4 text-center border-solid text-neutral">
    <div class="py-4 bg-pink-200 rounded-t">
      <%= link_to category.name, category_path(category), class: "md:hover:underline md:hover:font-bold md:hover:text-white" %>
    </div>
    <div class="flex items-end py-4 text-sm text-white rounded-b justify-evenly bg-base-content">
      <div class="w-1/2">
        <%= link_to "EDIT", edit_category_path(category), class: "md:hover:text-base md:hover:font-bold" %>
      </div>
      <div class="w-1/2">
        <%= link_to "DELETE", category_path(category), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "md:hover:text-base md:hover:font-bold"  %>  
      </div>
    </div>
  </div>
<% end %>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <div class="py-2 font-medium text-neutral">
      <%= form.label :name %>
    </div>
    <div><%= form.text_field :name, id: :category_name, class: "rounded h-10 w-52 pl-2 focus:outline-none focus:ring focus:border-red-800"%></div>
  </div>

  <div class="py-6">
    <div class="text-center text-white"><%= form.submit "Create", class: "w-52 h-10 rounded bg-neutral btn btn-outline" %></div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= render "shared/sidebar" %>
<div class="overflow-hidden grow">
    <% if notice.present? %>
        <div role="alert" class="alert alert-success">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 stroke-current shrink-0" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
            <span><%= notice %></span>
        </div>
    <% end %>
    <div class="flex items-center justify-center h-screen">
        <div class="flex flex-col items-center justify-center h-screen">
            <div class="flex flex-col items-center justify-center bg-pink-200 shadow-2xl rounded-2xl w-96 h-60">
                <h1 class="py-4 text-xl font-semibold text-center text-white bg-neutral w-96">Edit Category</h1>
                <div class="py-3">
                <%= render 'form', category: @category %>
                <div>
                <div class="mb-12 text-center">
                    <%= link_to "See Categories", categories_path, class: "link link-primary text-base font-medium" %> 
                </div>
            </div>
        </div> 
    </div>
</div>

app/views/categories/index.html.erb
<%= render "shared/sidebar" %>
<div class="overflow-hidden grow">
    <div class="flex flex-row items-end justify-start w-full pl-12 h-36">
        <div class="z-40 mb-4 text-5xl font-black text-purple overflow">
            Categories
        </div>
        <div class="flex items-center justify-center w-24 h-8 m-4 text-white rounded-full bg-neutral md:hover:font-bold md:hover:h-10 md:hover:w-28">
            <%= link_to "+ Category", new_category_path%>
        </div>
    </div>
    <% if @categories.present? %>
        <div class="flex w-full h-screen mx-12 my-10 overflow-y-auto text-2xl font-medium my-15" >
            <div class="flex flex-wrap content-start">
                <%= render "category_list" %>
            </div>
        <div>
    <% else %>
        <div class="flex justify-center pt-10 text-2xl font-medium">
            No category created
        </div>
    <% end %>
</div>

app/views/categories/new.html.erb
<%= render "shared/sidebar" %>
<div class="overflow-hidden grow">
    <% if notice.present? %>
        <div role="alert" class="alert alert-success">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 stroke-current shrink-0" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
            <span><%= notice %></span>
        </div>
    <% end %>
    <div class="flex flex-col items-center justify-center h-screen">
        <div class="flex flex-col items-center justify-center bg-pink-200 shadow-2xl rounded-2xl w-96 h-60">
            <h1 class="py-4 text-xl font-semibold text-center text-white bg-neutral w-96">Create Category</h1>
            <div class="py-3">
            <%= render 'form', category: @category %>
            <div>
            <div class="mb-12 text-center">
                <%= link_to "See Categories", categories_path, class: "link link-primary text-base font-medium" %> 
            </div>
        </div>
    </div>
</div>

app/views/categories/show.html.erb
<%= render "shared/sidebar" %>
<div class="overflow-hidden grow">   
    <div class="flex items-center justify-center h-screen">    
        <div class="w-full h-full">
            <%= render "shared/notice" %>
            <div class="flex flex-row items-end justify-start w-full pl-12 h-36">  
                <div class="mb-4 text-5xl font-black text-purple">
                    <%= @category.name %>
                </div>
                <div class="flex items-center justify-center w-24 h-8 m-4 text-white rounded-full bg-neutral md:hover:font-bold md:hover:h-10 md:hover:w-28">
                    <%= link_to "+ Task", new_category_task_path(@category)%>
                </div>
            </div>
                <div class="flex w-full h-screen mx-12 my-10 overflow-y-auto text-xl font-medium my-15" >
                    <div class="flex flex-col items-center w-full pt-4 ml-4 h-2/3">
                    <% if @tasks.present? %>
                        <%= render "shared/task_list" %>
                    <% else %>
                        <div class="flex justify-center pt-10 text-2xl font-medium">
                            No task added
                        </div>
                    <% end %>
                    </div>
                    <div class="flex flex-col items-center w-full pt-4 ml-4 h-2/3">
                        <%= render "shared/task_today" %>
                    </div>
                <div>         
        </div> 
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="valentine">
  <head>
    <title>JournalApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.7.2/dist/full.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com"></script>
    <%= javascript_importmap_tags %>
  </head>
  
  <body>
      <div class="flex h-screen">
        <%= yield %>  
      </div>
  </body>
</html>

app/views/main/home.html.erb
<%= render "shared/sidebar" %>
<div class="overflow-hidden grow">
    <% if notice.present? %>
        <div role="alert" class="alert alert-success">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 stroke-current shrink-0" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
            <span><%= notice %></span>
        </div>
    <% end %>  
    <div class="flex flex-col items-center justify-center h-screen">
        <div class="text-4xl font-bold">
            Welcome to Journal App       
        </div>
    </div>
</div>

app/views/shared/_notice.html.erb
<% if notice.present? %>
    <div class="z-40 flex flex-row justify-center w-1/3">
        <div role="alert" class="alert alert-success">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 stroke-current shrink-0" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
            <span><%= notice %></span>
        </div>
    </div>
<% end %>

app/views/shared/_sidebar.html.erb
<div class="flex-none h-full w-72 bg-neutral">
    <div class="flex flex-col h-full ">
        <div>
            <div class="pt-4 text-xl italic font-black text-center text-red-100">
                JOURNAL
            </div>    
            <div class="flex flex-row justify-center mt-3">
                <div class="flex items-center avatar">
                    <div class="w-16 h-16 rounded-full ring ring-primary ring-offset-base-100 ring-offset-2">
                        <img src="https://daisyui.com/images/stock/photo-1534528741775-53994a69daeb.jpg" />
                    </div>
                </div>
                <div class="ml-6">
                    <div class="text-lg font-bold text-white"><%= current_user.email %></div>
                    <div class="py-1 text-xs font-bold text-red-100">User</div>
                    <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "link link-secondary text-base font-semibold text-red-200" %>                   
                </div>
            </div>
            <div class="flex justify-center w-full mt-16 mb-3">
                <div class="flex items-center justify-center">
                    <%= link_to "My Categories", categories_path, class: "text-sm text-purple font-bold btn btn-outline btn-primary w-56 " %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_task_list.html.erb
<div class="w-2/3">
  <% @tasks.each do |task| %>
    <div class="flex justify-between border-b-2 border-neutral">
      <div>
        <%= task.title %>
      </div>
      <div class="flex grid grid-cols-3 my-2 text-sm divide-x divide-neutral">
        <div class="flex justify-center"><%= link_to "VIEW", category_task_path(task.category_id, task) %></div>
        <div class="flex justify-center"><%= link_to "EDIT", edit_category_task_path(task.category_id, task) %></div>
        <div class="flex justify-center pl-2"><%= link_to "DELETE", category_task_path(task.category_id, task), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %></div>
      </div> 
    </div>
  <% end %>
</div>

app/views/shared/_task_today.html.erb
<div class="overflow-y-auto border-2 rounded w-96 border-neutral h-3/4 bg-neutral">
<% tasks_due_today = Task.where(date: Date.today) %>
    <% if tasks_due_today.present? %>
        <div>
            <div class="py-2 text-center text-white">Due today</div>
            <% tasks_due_today.each do |task| %>
                <div class="px-4 py-2 m-3 bg-pink-200 rounded"><%= link_to task.title, category_task_path(category_id: task.category_id, id: task.id) %></div>
            <% end %>
        </div>
    <% else %>
        <div class="flex items-center justify-center h-full text-white">No task due today.</div>
<% end %>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: [@category, @task], local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div>
    <div class="py-2 font-medium text-black">
      <%= form.label :title %>
    </div>
    <div>
      <%= form.text_field :title, class: "rounded h-10 w-52 pl-2" %>
    </div>
  </div>

  <div>
    <div class="py-2 font-medium text-black">
      <%= form.label :description %>
    </div>
    <div>
      <%= form.text_area :description, class: "rounded h-36 w-52 p-2" %>
    </div>
  </div>

  <div>
    <div class="py-2 font-medium text-black">
      <%= form.label :date %>
    </div>
    <div>
      <%= form.date_field :date, class: "rounded h-10 w-52 pl-2" %>
    </div>
  </div>

  <div class="flex flex-col items-center justify-center mt-8 mb-4 actions">
    <div class="text-center text-white"><%= form.submit "Create", class: "w-52 h-10 rounded bg-neutral btn btn-outline" %></div>
  </div>
<% end %>
 

app/views/tasks/edit.html.erb
<%= render "shared/sidebar" %>
<div class="overflow-hidden grow">
    <% if notice.present? %>
        <p class="bg-green-500 notice"><%= notice %></p>
    <% end %>
    <div class="flex items-center justify-center h-screen">
        <div class="flex flex-col items-center justify-center h-screen">
            <div class="flex flex-col items-center justify-center h-auto bg-pink-200 shadow-2xl rounded-2xl w-96">
                <h1 class="py-4 text-xl font-semibold text-center text-white bg-neutral w-96">Edit Task</h1>
                <div class="py-3">
                    <%= render 'form', task: @task %>
                <div>
                <div class="mb-12 text-center">
                    <%= link_to "Back to Tasks", category_path(@category), class: "link link-primary text-base font-medium" %> 
                </div>
            </div>
        </div> 
    </div>
</div>

app/views/tasks/new.html.erb
<%= render "shared/sidebar" %>
<div class="overflow-hidden grow">
    <% if notice.present? %>
        <p class="bg-green-500 notice"><%= notice %></p>
    <% end %>
    <div class="flex items-center justify-center h-screen">
        <div class="flex flex-col items-center justify-center h-screen">
            <div class="flex flex-col items-center justify-center h-auto bg-pink-200 shadow-2xl rounded-2xl w-96">
                <h1 class="py-4 text-xl font-semibold text-center text-white bg-neutral w-96">New Task</h1>
                <div class="py-3">
                    <%= render 'form', task: @task %>
                <div>
                <div class="mb-12 text-center">
                    <%= link_to "Back to Tasks", category_path(@category), class: "link link-primary text-base font-medium" %> 
                </div>
            </div>
        </div>
    </div>
</div>

app/views/tasks/show.html.erb
<%= render "shared/sidebar" %>
<div class="overflow-hidden grow">
    <% if notice.present? %>
        <p class="bg-green-500 notice"><%= notice %></p>
    <% end %>
    <div class="flex justify-center h-screen">
        <div class="w-1/3 p-4 mt-40 border-solid rounded shadow-2xl h-72 border-neutral">
            <div class="flex justify-end pr-8 text-base">
                <%= @task.date %>
            </div>
            <div class="">
                <div>
                    <div class="pb-2 text-2xl font-bold">
                        <%= @task.title %>
                    </div>
                    <div class="h-32 pb-3 text-xl">
                        <%= @task.description %>
                    </div>
                </div>
                <div>
                    <div class="text-center">
                        <div><%= link_to "<< Back to task", category_path(@category) %></div>
                    </div> 
                </div>
            </div>
        </div>  
    </div>
</div>